### ISSUE TITLE
file date

### ISSUE THREAD

**Issue by lisong** [thejoshwolfe/yauzl#28]
how to keep the file's origin date when unzip? and all origin attributes.  when I do unzip the files,and use yazl zip the files, and compare the two zip files md5 does not equel.

**Comment by lisong** [comment]
and all origin attributes

**Comment by thejoshwolfe** [comment]
see: https://github.com/thejoshwolfe/yauzl#getlastmoddate

other attributes can be found in the `externalFileAttributes` field. The format of `externalFileAttributes` is not standardized, but you can try `chmod()` with `externalFileAttributes >> 16`. This is the format `yazl` uses.

regarding matching md5 with yazl, it's going to be nearly impossible to get a .zip file created by a different zip file library to match a .zip file produced by yazl. For example, [see here](https://github.com/thejoshwolfe/yazl#external-file-attributes).

if you're talking about a yazl-created .zip file being extracted and recreated with yazl, then getting a matching md5 should be doable. make sure the above two properties are set correctly, and make sure the order of entries is the same in both. i haven't tried to do this myself, but it should work. if you run into trouble, open an issue with yazl, because it will probably be more relevant to yazl than to yauzl at that point.

**Comment by lisong** [comment]
thanks.  i was test yazl that is ok. other unzip soft like the shell cmd unzip or the mac unzip soft keep the origin attributes

**Comment by thejoshwolfe** [comment]
yes. yauzl is technically not an unzip utility; it's just a library. the example in `examples/unzip.js` is a command line utility, but it's not polished. it's just for example purposes.
