### ISSUE TITLE
Some directory file names isn`t end with /

### ISSUE THREAD

**Issue by f111fei** [thejoshwolfe/yauzl#32]
Steps to Reproduce:
Download: https://github.com/f111fei/test-files/raw/b124ebeb0ac1378f1335b0601485bd926743031f/yauzl-test.zip

Run: `node index.js`

Get Output:

```
Current FileName: extension/1
Current FileName: extension/1/2
c:\Users\xzper\Desktop\yauzl-test\index.js:23
if (err) throw err;
^

Error: EEXIST: file already exists, mkdir 'c:\Users\xzper\Desktop\yauzl-tes
t\extension\1'
at Error (native)
```
`entry` is a directory, but `entry.filename` isn`t end with '/'

**Comment by thejoshwolfe** [comment]
can you provide an example .zip file that demonstrates this problem?

**Comment by f111fei** [comment]
@thejoshwolfe  sorry. I reedit this issue.

**Comment by thejoshwolfe** [comment]
Even InfoZip's `unzip` command line utility cannot extract this zip file:

```
$ unzip test.zip 
Archive:  test.zip
 extracting: extension/1             
checkdir error:  extension/1 exists but is not directory
                 unable to process extension/1/2.
checkdir error:  extension/1 exists but is not directory
                 unable to process extension/1/2/README.md.
```

Do you know what zipfile program created this zip file? Do you know of a zipfile extractor that can read this zipfile?

**Comment by f111fei** [comment]
Create by WinRAR. And WinRAR read this zipfile. It`s no prob.

**Comment by thejoshwolfe** [comment]
I'll have to look into how WinRAR indicates that files are directories. I don't see any clues to distinguish between a directory and an empty file in this zipfile. Not even the NTFS extra field (which they're using) is able to specify that an entry is a directory, so I don't know where they could be hiding that metadata.

It looks like my use of WinRAR will be limited due to licensing issues. I'm not sure I'm willing to use a free trial or pirate the software on principle; I'd rather not support non-free software if I can avoid it. But if you're willing to help out on this issue, I'll give you some experiments to run. Please extract [this zipfile](http://wolfesoftware.com/winrar-test.zip), and then zip up the resulting directory `winrar-test` with WinRAR and send it to me. I'd like to see how WinRAR distinguishes between empty files and empty directories.

**Comment by f111fei** [comment]
![1](https://cloud.githubusercontent.com/assets/7069719/16004229/05ce7d66-3193-11e6-8509-825fe8921abf.png)
sorry. I use chinese os.

Maybe WinRAR create a damaged zip file that cannot be unziped by other programs.

**Comment by thejoshwolfe** [comment]
would you be willing to do the experiment I described? Extract and then re-zip with WinRAR so I can see how WinRAR handles the content? In case the link didn't come through, here's the link again for the zipfile I'm talking about:

http://wolfesoftware.com/winrar-test.zip

**Comment by f111fei** [comment]
https://github.com/f111fei/test-files/raw/master/winrar-test.zip

This is re-zip with WinRAR. It`s no problem use `yauzl` to extract.

I think the first `test.zip` is damaged for some reason.

**Comment by thejoshwolfe** [comment]
I agree that that second zip file looks fine. I don't know what happened with the first. If you find out a way to create these "broken" zipfiles reliably, let me know.
