### ISSUE TITLE
Executables fail to run if started too soon after being unzipped

### ISSUE THREAD

**Issue by sean-mcmanus** [thejoshwolfe/yauzl#41]
This is pseudocode with lots of stuff like error handling removed.

``` js
yauzl.fromFd(fd, { lazyEntries: true }, (err, zipfile) => {
                zipfile.readEntry();
                zipfile.on('entry', (entry: yauzl.Entry) => {
                        zipfile.openReadStream(entry, (err, readStream) => {
                            mkdirp.mkdirp(path.dirname(path), { mode: 0o775 }, (err) => {
                                readStream.pipe(fs.createWriteStream(path, { mode: fileMode }));
                                readStream.on('end', () => {
                                    zipfile.readEntry();
                                });
                            });
                        });
                    }
                });
                zipfile.on('end', () => {
                    resolve();
                });
            });
        })
err = process.spawn();
```

The bug is that the process.spawn returns -4082 (0xFFFFF00E), which means the process isn't finished being written yet. It looks like something isn't flushing the buffer soon enough. Sitting in a busy wait loop will eventually cause the process.spawn to succeed. I tried to somehow close or flush the stream buffer but nothing fixed it.

We hit this bug with the implementation of our C++ VS Code extension, but we worked around it by installing the .exe we need to launch before installing the the other executables.

**Comment by thejoshwolfe** [comment]
i believe the problem is that a read stream's end event doesn't indicate that the data has been flushed to the fs. only a write stream can know that. it looks like both the [close](https://nodejs.org/api/stream.html#stream_event_close) and [finish](https://nodejs.org/api/stream.html#stream_event_finish) events are relevant to this problem. if you're on windows, i think you need to wait for the close before you can execute a file.

a naive change would be to call zipfile.readEntry in response to the above-mentioned event instead of the read stream's end event. however, that's probably more throttling than you need for a zipfile with many small entries.

optimally you might consider using an async latch pattern to make sure that the final resolve function waits for the close events, but the zipfile streaming does not. use one increment/decrement pair for the entire zipfile, incrementing before opening and decrementing on zipfile end, and use an increment/decrement pair for each write stream you open, decrementing on write stream close.

i haven't found any node latch libraries that fit this usecase perfectly (i also haven't looked very hard), so i can't recommend any existing code. however the pattern is pretty simple to implement yourself if you're so inclined. the pattern is to run a function when a counter reaches zero no matter where the decrement happens.

this might be a common enough use case that i should add an example to the `examples/` directory demonstrating it.

**Comment by rafis** [comment]
You need to change `readStream.on('end', ...)` to `writeStream.on('close', ...)` as noted by me [here](https://github.com/thejoshwolfe/yauzl/issues/43). The author of the library, @thejoshwolfe needs also to change this or at least put a note in readme.

**Comment by sean-mcmanus** [comment]
Okay, thanks. I'll try that later.

**Comment by thejoshwolfe** [comment]
@sean-mcmanus, I'm not sure what you're referring to when you say i need to "change this". Do you mean change the example in the readme?

As i mentioned in my (admittedly rambling) comment above, replacing `readStream` `end` with `writeStream` `close` is the easiest solution, but it isn't quite optimal. I insist that the example in the readme is not wrong or misleading; it's simply not designed to solve the problem in this issue or in #43; it does not "know" when the file data is done writing to disk. That code is missing from the readme because this is a zipfile reading library, not a file system writing library. The fine details of how to pipe a node stream to a file system are outside the scope of this library and its readme.

That being said, i also admit that it's useful to know some fundamental asynchronous patterns that are relevant to using this library, and I'd like to add something in the `examples/` directory to demonstrate that. That is why this issue is still open as a doc issue. (the examples are docs.)

**Comment by thejoshwolfe** [comment]
I've enhanced the `unzip.js` example to show how to track the number of open file handles and run some code when the count reaches 0. I've also removed the `createWriteStream` calls from the README example.
