### ISSUE TITLE
unsupport unzip java uploaded .zip file

### ISSUE THREAD

**Issue by zouyixiong** [thejoshwolfe/yauzl#45]
when unzip a java uploaded .zip file from buffer , throw error "invalid comment length. expected: 2. found: 0", but when we comment the bellow verify code, and the file unzips success:

``` js
if (commentLength !== expectedCommentLength) {
        return callback(new Error("invalid comment length. expected: " + expectedCommentLength + ". found: " + commentLength));
      }
```

about java upload .zip file, the buffer count is less then node.js: http://stackoverflow.com/questions/34643660/missing-bytes-when-uploading-zip-file-with-multipart-form-data-using-java

can we just deprecate the verify code above ?

**Comment by thejoshwolfe** [comment]
The error you're getting from yauzl is reporting that there are 2 extra bytes at the end of the zip file, specifically after the End of Central Directory Record Signature.

The stackoverflow link you gave indicated that a file was being opened in text mode instead of binary mode. This kind of mistake has disastrous ramifications on binary files, potentially making them irrecoverably corrupted. Getting two bytes at the end of the file is just one of many problems you could get from that mistake. For example, if you have a zipfile with 10 or 13 entries, and you open the file in text mode on windows, the number of entries in the file will be changed to 2573, and 1 byte will be added in the middle of the End of Central Directory Record binary structure, corrupting all fields that come after the entry count. But any number of entries other than 10 or 13 would show no corruption problem.

The error you're getting from yauzl is useful for detecting serious errors, and I'm not sure that your situation is really as simple as you think it is. It could be that there you are dealing with a data corruption problem somewhere in the java code that is providing you with zipfiles, and the "invalid comment length" error is just the tip of the iceberg, the canary in the coal mine: it's a harmless-looking warning that something else is horribly wrong.

There is another possibility, which is that the data corruption issue is really just appending two garbage bytes at the end of the file, and that's all there is to the explanation. If it's that simple, there's a workaround you can do to fix your input before providing it to yauzl. But if you should be sure you know exactly why your zipfiles are being corrupted before trying to patch them. If the problem is the text-vs-binary problem described above, there is no way to patch the file to repair it.
