### ISSUE TITLE
Allow settings custom character encoding for files within the zip

### ISSUE THREAD

**Issue by rightaway** [thejoshwolfe/yauzl#51]
In the code below, what is the encoding of the file referred to by `readStream`?

```js
    yauzl.open('file.zip', (err, zipfile) => {
      if (err) throw err
      zipfile.on('entry', (entry) => {
        zipfile.openReadStream(entry, (err, readStream) => {
          if (err) throw err
          // What is readStream encoding? 
        })
      })
    })
```

The README says

> Zip files officially support charset encodings other than CP437 and UTF-8, but the zip file spec does not specify how it works. This library makes no attempt to interpret the Language Encoding Flag.

It would be helpful if there can be a way to tell yauzl the encoding of the file if you know what it is. It's more efficient if yauzl does it directly than having to pipe it through a conversion stream like `iconv-lite`.

**Comment by thejoshwolfe** [comment]
It sounds like you're talking about reading a file as a text file encoded in a charset such as UTF-8 or ISO-8859-1 or something. As you seem to be aware, you can do that outside yauzl by piping the file contents through `iconv-lite`, as you suggested, or some other way of converting bytes to strings.

The zipfile format is a binary format with different kinds of data. Some of the data is strings, like filenames, and some of the data is bytes, like the contents of files. The data you get from `readStream` in the example above does not have any encoding as defined by the zipfile specification. The closest you get to such an encoding is a hint in the general purpose bit flag that the file is "apparently an ASCII or text file", but yauzl ignores this. The language encoding flag is only related to the strings in the zipfile format, such as filenames, not the contents of files.

> It's more efficient if yauzl does it directly than having to pipe it through a conversion stream like iconv-lite.

I don't think this is true, since yauzl would implement such a conversion by doing precisely what you're suggested would happen outside yauzl. Can you be more specific in how you suggest yauzl does the conversion to be more efficient?

**Comment by thejoshwolfe** [comment]
Closing this issue, assuming my comment above addressed the original question/concerns. Please reopen if you'd like to continue the conversation.
