### ISSUE TITLE
No entry for containing directory?

### ISSUE THREAD

**Issue by panta82** [thejoshwolfe/yauzl#52]
If there is a single directory inside the archive that's wrapping everything else, yauzl doesn't seem to emit an entry for that directory.

Example zip structure:
```
test/
    file.txt
    subdir/
        file2.txt
```

Test program:
```javascript
var yauzl = require("yauzl");

yauzl.open(__dirname + "/test.zip", {lazyEntries: true}, function (err, zipfile) {
	if (err) throw err;
	zipfile.readEntry();
	zipfile.on("entry", function(entry) {
		console.log(entry.fileName);
		zipfile.readEntry();
	});
});
```

Output:
```
test/file.txt
test/subdir/
test/subdir2/
test/subdir2/file2.txt
```

I was expecting the output to start with `test/`.

The zip file is created using default Windows right-click thing. You can find the demo app and zip file I used here: https://github.com/panta82/yauzl-test

**Comment by thejoshwolfe** [comment]
Sorry for the delayed response.

From my testing with the Windows `Right Click | Send to | Compressed (zipped) folder`, Windows simply omits a directory entry in the zipfile for the folder you initially right-clicked on. Directories within it get their own entries, but the top level folder does not. Your `test.zip` that you linked confirms this situation is happening to you too.

Some background might be appropriate here: Zip files are not designed to archive directory entries. There is no mechanism in the zip file specification for storing directories. Instead, you store the path to each file in the zipfile through directories that are implicitly created as needed. For example, a zipfile might contain a single entry, which is a file with a path `a/b/c.txt`. This file entry would require that the zipfile extractor create directories `a/` and `a/b/` in order to extract `c.txt` into them.

However, there are two design flaws with this omission:

1. There is no way for a zipfile to contain an empty directory.
2. There is no way to specify the permissions or other metadata for directories in a zipfile.

These shortcomings led zipfile users to invent their own convention for storing directory entries. The convention is that if a filename ends with a `/`, then it's just a directory, not a file. This convention is universally accepted and implemented, and is (surprisingly) still non-standard, despite the standard publishing multiple updates since this convention became common practice.

All that background really means that the Windows Compressed Folder function is not violating the specification by omitting a directory entry. (It is, however, inconsistent for it to still include directory entries for some directories and not all of them; it's honestly probably a bug in that utility, but it isn't technically incorrect behavior.)

So now on to what you and i should do about your situation right now (or two months ago; again, sorry for the delayed response.). With the understanding that directory entries are not required by the zip file spec, and a file entry implicitly requires its parent directories to be created, does that solve your issue? Were you hoping to get some specific metadata about the root directory, like the permission bits or something? If so, I can't help you, because that information is simply not in the zipfile.

**Comment by panta82** [comment]
Thank you for the through explanation of the issue.

> So now on to what you and i should do about your situation right now (or two months ago; again, sorry for the delayed response.). With the understanding that directory entries are not required by the zip file spec, and a file entry implicitly requires its parent directories to be created, does that solve your issue? Were you hoping to get some specific metadata about the root directory, like the permission bits or something? If so, I can't help you, because that information is simply not in the zipfile.

I was trying to smartly remove a common holding directory from the zip archive. The same thing Mac unarchiver does, only in reverse. :)

Given the circumstances, I don't think you should do anything. Zip is what it is.

I'll just implement my functionality in 2 steps, unzip into temp, then move the files with or without a common dir.

Thanks.
