### ISSUE TITLE
Is there any way to get entry file permissions?

### ISSUE THREAD

**Issue by adam-lynch** [thejoshwolfe/yauzl#57]
### Background

I'm working on [nw-builder](https://github.com/nwjs-community/nw-builder) which was previously using [decompress-zip](https://www.npmjs.com/package/decompress-zip). In an event handler (like `entry`), entries were pushed into an array (with `entry.mode` that decompress-zip gives us) and then when finished, the files were looped over and to correct their permissions. We found a problem with Chromium symlinks though so I've moved onto [extract-zip](https://github.com/maxogden/extract-zip) (a simple wrapper for yauzl).

---

How can I get the file permissions for entry files? Are they exposed somehow via what's passed to an `entry` event handler?

---

I don't mind forking extract-zip to add this ability (right now it has a default for directories and a default for files it applies to everything).

**Comment by thejoshwolfe** [comment]
When implementing yazl, a zipfile creator, i discovered the convention that some zipfiles store the unix stat mode in the upper 16 bits of an entry's external file attributes. see https://github.com/thejoshwolfe/yazl/blob/master/README.md#external-file-attributes

This is not "standard" behavior as it is not specified in the zipfile spec. For this reason yauzl does not have any api for getting the unix permission bits for an entry. However, if you'd like to take responsibility for checking for unconventional zipfiles yourself, you can start with:

```js
var mode = entry.externalFileAttributes >>> 16;
```

This corresponds to the `stats.mode` you would get from [fs.stat()](https://nodejs.org/api/fs.html#fs_fs_stat_path_callback).

**Comment by adam-lynch** [comment]
Thanks @thejoshwolfe!

I'll give that a go. I assume that if other libraries expose file permissions then it's using this and I guess when you say "unconventional", it doesn't necessarily mean "uncommon", just that it's not spec-compliant.

**Comment by adam-lynch** [comment]
Sorted, thanks

**Comment by thejoshwolfe** [comment]
> I assume that if other libraries expose file permissions then it's using this

That's the part I haven't checked. I know it works well to produce zipfiles using this convention, but I've learned a lot from trying to read zipfiles about how ridiculous third party libraries can be creating zipfiles that bend or even flat out break the rules. You very well may be safe with that assumption, but maybe not. I don't know.

I'd like to be able to say "technically x, but in practice y", but i've learned that in practice people don't follow the rules when making zipfiles. People will do unexpected things, and so you can either try to handle everything, or eventually draw the line and not support something.

yauzl takes a pretty strict approach in only supporting what is standard (or at least allowed in the standard), and it turns out to be a pretty unusual design philosophy among zipfile readers. For example, Info-ZIP's `unzip` command line program will bend over backward to tolerate flagrant spec violations and malformed zipfiles in order please as many users as possible. If you want to take that approach in this regard, you'll need to do a lot of research, which will take time (probably years) of collecting data and watching out for issues.

Or you could do a best-effort implementation and support the permissions as best you can, and when it doesn't work, you don't worry about it. This is probably how you'll start, even if you intend to someday accomplish the former.

Best of luck.
