### ISSUE TITLE
More files than entryCount

### ISSUE THREAD

**Issue by RickDT** [thejoshwolfe/yauzl#60]
My apologies if this is addressed elsewhere. I couldn't find it in the README or Issues.

I have a zip file with ~70K files, but the file catalog says it has only 14,202. 
On my Mac:
`unzip -Zh file.zip` yields "Zip file size: 139476498 bytes, number of entries: 14202"
`unzip -l file.zip` yields "557051138 ... 79738 files"

I'm not sure where the discrepancy comes from, but if I unzip the file using `unzip` on the command line, or double click it in Finder, all ~70K files unzip.

Using yauzl, it only unzips the first 14202 files and then ends/closes. I tried with my own implementation and also using `examples/unzip.js` in the repo.

Is there some way to configure yauzl to unzip all the files in the zip, regardless of the reported number of entries?

**Comment by thejoshwolfe** [comment]
Is it possible to send me the zipfile that demonstrates this issue?

**Comment by thejoshwolfe** [comment]
Also, does `unzip` produce any warnings about the file being corrupted and then say "`(attempting to process anyway)`"? All my attempts to recreate what you're describing with odd zipfiles result in warnings like that from `unzip`. For example this:

```
$ unzip -l test2.zip 
Archive:  test2.zip
warning [test2.zip]:  75 extra bytes at beginning or within zipfile
  (attempting to process anyway)
  Length      Date    Time    Name
---------  ---------- -----   ----
        5  2014-08-18 09:30   b.txt
---------                     -------
        5                     1 file
```

**Comment by RickDT** [comment]
https://drive.google.com/file/d/0Byq8vle3i_j7QUNUYUQ0ZXU0RGs/view?usp=sharing

Here's a test file that exhibits this behavior. I created it by running `react-native init one` and then copying the `one` folder as `two`, `three`, and `four`. This resulted in 71,609 smallish files.

I zipped it all up by selecting the one, two, three, four folders in Finder and right-clicking, choosing Compress.

`unzip -l test.zip` does not show the type of error you mentioned. It lists all files and notes `83349 files` in the footer of the output.

When I run `node examples/unzip.js test.zip`, it unzips the `four` folder and ends early.

**Comment by thejoshwolfe** [comment]
Great! I've reproduced the issue. I'll let you know what I discover. Thanks for the test case.

**Comment by thejoshwolfe** [comment]
Just to let you know, I'm still working on this. The first step in this project is to fix `tools/hexdump-zip.js` to work with large files without running out of memory, which is taking some time. (And also I've been pretty busy lately, blah blah blah.) I have not forgotten or given up! Thank you for your patience.

**Comment by RickDT** [comment]
Thanks! I wish I had time to jump in and help, so I understand the time constraints. For now, we're unzipping via `child_progress.spawn` and using the `unzip` CLI on Linux.

**Comment by thejoshwolfe** [comment]
After much [yak shaving](https://en.wiktionary.org/wiki/yak_shaving) (rewriting my [zip file analysis tool](https://github.com/thejoshwolfe/hexdump-zip) to be more memory conservative (and developing the [programming language](https://github.com/zig-lang/zig) it is written in)), I've figured out what the issue is with this zipfile. It's pretty much the same problem as issue #69.

When the Mac Archive Utility needs to write the 16-bit entry count in the end of central directory record, it doesn't check for overflow, and simply writes the lower 16 bits of the entry count. In the OP here, the real entry count was 79738 or 0x1377a, and Archive Utility wrote 14202 or 0x377a in the zip file metadata. In the zipfile you linked me, the numbers were 0x14595 and 0x4595.

This means that the metadata is an outright lie about the number of entries in the zipfile. This is absolutely a bug in Archive Utility, and it's a nasty one too. The correct behavior would have been to use ZIP64 format, but Archive Utility has no idea what that is.

There may or may not be any way to correctly and reliably recover from this corruption. I'm still thinking about it.

**Comment by RickDT** [comment]
Wow, that's pretty nasty. Thanks for the detailed explanation!

**Comment by overlookmotel** [comment]
@RickDT Please see https://github.com/thejoshwolfe/yauzl/issues/69#issuecomment-383424896
