### ISSUE TITLE
'fs'dependency not found

### ISSUE THREAD

**Issue by saothienhat** [thejoshwolfe/yauzl#62]
Hi,
During using this module, I found that the 'yauzl/index.js' file require 'fs' module which is no longer existed. So, who can I resolve this issue ?

I wonder if Is there any replacement for 'fs' ?

**Comment by thejoshwolfe** [comment]
Are you trying to use yauzl in a browser? yauzl is designed to work in Node.js, and `fs` is part of the standard library. Browsers have different io apis, and yauzl does not support that environment currently.

**Comment by saothienhat** [comment]
Hi @thejoshwolfe 
I use yauzl for local files not browser. I wonder that if 'fs' is standard library, why it is not exist now.
And "https://www.npmjs.com/package/fs" is repository of mentioned 'fs', right ?

If the 'fs' is not existed now, do we have any way to use yauzl ?

**Comment by thejoshwolfe** [comment]
According to the node.js homepage, the latest node version is 8.6.0: https://nodejs.org/en/

According to the node 8.6.0 docs, the `fs` module still exists: https://nodejs.org/api/fs.html

The `fs` module has been a stable core component of node.js for years. After some searching I don't see any news about deprecating it.

The npm module named `fs` you posted is not a real module; it's some special thing in the npm repository, because `fs` is a builtin module.

What is the result of this command for you:

```
node --version
```

**Comment by saothienhat** [comment]
Sorry, it is my wrong code. After checking, I found that my logic code run in a brower :( . So, Please ignore this issue. Thank for your support
