### ISSUE TITLE
 Error: end of central directory record signature not found  - when unzip and rezip

### ISSUE THREAD

**Issue by RadhaEY** [thejoshwolfe/yauzl#72]
```
Error: end of central directory record signature not found
    at D:\home\site\wwwroot\node_modules\yauzl\index.js:183:14
    at D:\home\site\wwwroot\node_modules\yauzl\index.js:622:5
    at D:\home\site\wwwroot\node_modules\fd-slicer\index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)
```

I get above error , when I am trying to unzip a file  that has a folder inside and rezip only files. It works fine when I test from my local but when it is deployed on azure it fails. Could you please help me to understand the issue?

code : 

```
 function UnzipAll(zipName, res) {
            yauzl.open(zipName, { lazyEntries: true }, function (err, legacyZIPFile) {
                if (err) throw err;
                let newZIPFile = new yazl.ZipFile();
                legacyZIPFile.readEntry();
                legacyZIPFile.on("entry", function (entry) {
                    if (/\/$/.test(entry.fileName)) {
                        legacyZIPFile.readEntry();
                    } else {
                        legacyZIPFile.openReadStream(entry, function (err, readStream) {
                            if (err) throw err;
                            readStream.on("end", function () {
                                legacyZIPFile.readEntry();
                            });
                            newZIPFile.addReadStream(readStream, path.basename(entry.fileName));
                        });
                    }
                });
                legacyZIPFile.on("close", function () {
                    newZIPFile.end();                    
                     newZIPFile.outputStream.pipe(res).on("close", function () {
                    console.log("done");
                });
                    //*****remove the file
                    fs.unlink(zipName);
                });
            });
        }
```

**Comment by thejoshwolfe** [comment]
I recommend starting the `newZIPFile.outputStream.pipe(res)` sooner, such as immediately after creating the `new yazl.ZipFile()`, instead of waiting until the `legacyZIPFile` is finished reading.

I believe your issue is that `newZIPFile` is waiting to draw data out of the `readStream`s you add until `newZIPFile.outputStream` is piped. The entire pipeline needs to be flowing, so make sure the final output has somewhere to go.

If the pipeline backs up and stops, then your code will not get `readStream.on("end")` events, which means you'll stop reading entries, which means you'll never get to `legacyZIPFile.on("close")`, which means you'll never start piping `newZIPFile.outputStream`.

If the zipfile never gets properly created, then you'll definitely get a `Error: end of central directory record signature not found` when trying to read the incomplete zipfile.

That's my best guess as to what could be causing your problem.

Also the title of this issue says "invalid central directory file header". Did you mean "end of central directory record signature not found"?

**Comment by thejoshwolfe** [comment]
Please reopen if you have any further questions.
