### ISSUE TITLE
Help Needed to debug the error - End of central directory record signature not found

### ISSUE THREAD

**Issue by akshita31** [thejoshwolfe/yauzl#83]
I need to download a zip and then unzip it using yauzl. The code that I have does that most of the times but sometimes I get the - 'End of central directory record signature not found`  error which suggests that the downloaded file could not be put completely into the file stream and we started unzipping it.

I posted this question - https://stackoverflow.com/questions/49932297/downloading-a-zip-into-a-file-and-unzipping-it-using-nodejs-how-to-detect-when, but didnt get an answer yet.
Can you help me understand what is it that is going wrong and how to correct it. 
Apologies if this is not the right place to ask this.

**Comment by thejoshwolfe** [comment]
If you're getting an intermittent "End of central directory record signature not found" error, this is most commonly caused by the zipfile only being partially written when yauzl starts to read it.

The node fs stream piping API is, unfortunately, very easy to misuse. A common mistake is listening for a Readable `"end"` event instead of a Writable `"finish"` or `"close"` event to determine when the file is done being written. (And on windows, listening for `"finish"` instead of `"close"` will give you intermittent "Permission denied" errors, ugh.)

After looking briefly at your stackoverflow post, I would investigate the `await DownloadFile()` call to see if it's really finished writing the file when the promise is resolved.

> Apologies if this is not the right place to ask this.

It's hard to tell, but I believe this problem is outside of yauzl.

**Comment by akshita31** [comment]
Yes after reading a lot, I think it is probably because we are not waiting for the `finish` event , so the file is not completely flushed into the file before we are trying to unzip it. And yes I dont think it is a problem with yauzl. Thanks for the help. I am closing this now.
