### ISSUE TITLE
usage demo comes error: "TypeError: dest.on is not a function"

### ISSUE THREAD

**Issue by bi-kai** [thejoshwolfe/yauzl#90]
I run the usage demo:
```javascript
const yauzl = require("yauzl");

yauzl.open("./OMStarPS_npi.capacity_11.5.0.zip", {lazyEntries: true}, function(err, zipfile) {
  if (err) throw err;
  zipfile.readEntry();
  zipfile.on("entry", function(entry) {
    if (/\/$/.test(entry.fileName)) {
      // Directory file names end with '/'.
      // Note that entires for directories themselves are optional.
      // An entry's fileName implicitly requires its parent directories to exist.
      zipfile.readEntry();
    } else {
      // file entry
      zipfile.openReadStream(entry, function(err, readStream) {
        if (err) throw err;
        readStream.on("end", function() {
          zipfile.readEntry();
        });
        readStream.pipe('./');
      });
    }
  });
});
```

comes error: 
```
_stream_readable.js:501
  dest.on('unpipe', onunpipe);
       ^

TypeError: dest.on is not a function
    at AssertByteCountStream.Readable.pipe (_stream_readable.js:501:8)
    at D:\node\www\test\test-unzip\yauzl.js:19:20
    at D:\node\www\test\test-unzip\node_modules\yauzl\index.js:575:7
    at D:\node\www\test\test-unzip\node_modules\yauzl\index.js:631:5
    at D:\node\www\test\test-unzip\node_modules\fd-slicer\index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)
```

I just wanna unzip a zip file.

**Comment by thejoshwolfe** [comment]
Can you try running `example/unzip.js` on your zipfile?

If that doesn't work either, check the version of node you're using. For me, it's:

```
$ node --version
v8.10.0
```

**Comment by bi-kai** [comment]
```
PS D:\node\www\test\test-unzip> node -v
v8.11.1
PS D:\node\www\test\test-unzip> node .\yauzl.js
_stream_readable.js:582
  dest.on('unpipe', onunpipe);
       ^

TypeError: dest.on is not a function
    at AssertByteCountStream.Readable.pipe (_stream_readable.js:582:8)
    at D:\node\www\test\test-unzip\yauzl.js:19:20
    at D:\node\www\test\test-unzip\node_modules\yauzl\index.js:575:7
    at D:\node\www\test\test-unzip\node_modules\yauzl\index.js:631:5
    at D:\node\www\test\test-unzip\node_modules\fd-slicer\index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
```
what is the easiest way to unzip a zip file?

**Comment by thejoshwolfe** [comment]
try this code:

https://github.com/thejoshwolfe/yauzl/blob/master/examples/unzip.js

**Comment by bi-kai** [comment]
I have no idea about how to run you unzip.js, it's realy nether like a example nor a lib.

**Comment by bi-kai** [comment]
```
var yauzl = require("../");
```
where to place yauzl module?
I have no idea about how to run you unzip.js, it's realy nether like a example nor a lib.
I quite.

**Comment by thejoshwolfe** [comment]
Ah, yeah. Sorry. That require call is confusing. I've updated it with a comment explaining how to translate that to be useful outside of yauzl's source code directory structure.

I took another look at your code from the OP, and I don't know why I didn't see this before, but the problem is here:

```js
readStream.pipe('./');
```

You have to `pipe()` into a stream, not a file path. In my example I linked above I make a file write stream here:
https://github.com/thejoshwolfe/yauzl/blob/51010ce4e8c7e6345efe195e1b4150518f37b393/examples/unzip.js#L193 https://github.com/thejoshwolfe/yauzl/blob/51010ce4e8c7e6345efe195e1b4150518f37b393/examples/unzip.js#L196

There are lots of other kinds of streams you can pipe the file contents into.

**Comment by jfisher446** [comment]
The same issue got me as well. Thanks for the ask and the resolution!

**Comment by jfisher446** [comment]
Would it be prudent to modify the readme usage example to finish off with a file write, which I'd imagine would be most users' intents? I can also see why you'd leave the usage open as it is currently, but with this change, any user that's knowledgable enough to know that they're looking to stream it in a different fashing probably also knows the change that they'd need to make to accomodate their use..
Such as: 
```
                    let writeStream = fs.createWriteStream(entry.fileName);
                    readStream.pipe(writeStream);
                });
```

**Comment by thejoshwolfe** [comment]
That will often be incorrect, because you should really do a mkdirp beforehand, and at that point there'd be a lot of code distracting from the example.

I also include this line after the usage example:

> See also `examples/` for more usage examples.

And that directory contains fully written and working example code.

**Comment by jmeriksson** [comment]
I had the same problem but after spending a couple of hours going through the unzip.js file at https://github.com/thejoshwolfe/yauzl/blob/master/examples/unzip.js I managed to get around it.

Question for @thejoshwolfe 
Say that I don't want the unpacked files to be placed in the root directory, how do I go about specifying another directory where I want to place the unpacked files?

**Comment by andrewrk** [comment]
@jmeriksson that sounds like a question for StackOverflow, "how do I program in JavaScript/Node.js" rather than content that belongs in a GitHub issue for yauzl.

**Comment by thejoshwolfe** [comment]
@jmeriksson There may be a misunderstanding about the purpose of yauzl as a piece of software. yauzl is a fairly low-level software library for allowing node.js programs to comprehend zipfile-encoded data. This is not a command line tool.

The intended users of this library are already node.js developers who understand the node stream api and os api. Your question suggests that you're approaching this from a higher level perspective, like "how do i extract a zipfile" rather than "how do i integrate zipfile support into my software suite". I apologize if I'm wrong, but I don't know how to give an answer to your question in any way that is relevant to yauzl specifically as opposed to general node.js development.
